#!/usr/bin/env python3
"""Generate 16×16 1bpp katakana bitmap font header for ESP32 firmware."""

from PIL import Image, ImageDraw, ImageFont
import struct

# Katakana characters to include
KATAKANA = ''.join([
    # Base katakana (46)
    'アイウエオ',  # a i u e o
    'カキクケコ',  # ka ki ku ke ko
    'サシスセソ',  # sa si su se so
    'タチツテト',  # ta ti tsu te to
    'ナニヌネノ',  # na ni nu ne no
    'ハヒフヘホ',  # ha hi hu he ho
    'マミムメモ',  # ma mi mu me mo
    'ヤユヨ',      # ya yu yo
    'ラリルレロ',  # ra ri ru re ro
    'ワヲン',      # wa wo n
    'ヴ',          # vu
    # Voiced katakana (dakuten variants for visual variety)
    'ガギグゲゴ',  # ga gi gu ge go
    'ザジズゼゾ',  # za zi zu ze zo
    'ダヂヅデド',  # da di du de do
    'バビブベボ',  # ba bi bu be bo
    # Semi-voiced
    'パピプペポ',  # pa pi pu pe po
    # Small katakana
    'ァィゥェォ',  # small a i u e o
    'ッャュョ',    # small tsu ya yu yo
    # A few kanji for density
    '日月火水木金土年時間',
])

import sys

# Load font
font_path = '/System/Library/Fonts/ヒラギノ角ゴシック W3.ttc'
font = ImageFont.truetype(font_path, 16)

sys.stderr.write(f"Rendering {len(KATAKANA)} characters...\n")

# Generate glyph data
glyph_data = []
bmp_rows = []  # For visual preview

for ch in KATAKANA:
    img = Image.new('1', (16, 16), 0)
    draw = ImageDraw.Draw(img)
    bbox = draw.textbbox((0, 0), ch, font=font)
    # Center vertically within 16px
    ch_h = bbox[3] - bbox[1]
    yoff = (16 - ch_h) // 2 - bbox[1]
    draw.text((0, yoff), ch, font=font, fill=1)

    # Convert to 16 rows of uint16_t via load() pixel access
    px = img.load()
    row_data = []
    for r in range(16):
        bits = 0
        for c in range(16):
            if px[c, r]:
                bits |= (1 << (15 - c))
        row_data.append(bits)
    glyph_data.append(row_data)

    # Store visual preview
    lines = []
    for r in range(16):
        line = ''.join('*' if px[c, r] else ' ' for c in range(16))
        lines.append(line)
    bmp_rows.append((ch, lines))

# Output header
print("\n// Generated by fontgen.py")
print(f"// {len(KATAKANA)} characters")
print("#pragma once")
print("#include <stdint.h>")
print()

# Index table (code point -> index)
print("// Unicode code point list (sorted)")
print("static const uint16_t kata_codes[] = {")
for i, ch in enumerate(KATAKANA):
    sep = ',' if i < len(KATAKANA) - 1 else ' '
    print(f"  0x{ord(ch):04X}{sep}  // {ch}")
print("};")
print(f"static const int KATA_N = {len(KATAKANA)};")
print()

# Glyph bitmap data
print("// 16×16 1bpp glyph bitmaps (16 uint16_t per glyph)")
print("static const uint16_t kata_bitmaps[][16] = {")
for gi, rows in enumerate(glyph_data):
    ch = KATAKANA[gi]
    row_strs = ['0x{:04X}'.format(r) for r in rows]
    print(f"  {{ {', '.join(row_strs)} }},  // {ch} U+{ord(ch):04X}")
print("};")
print()

# Also generate a lookup function
print("// Lookup: code point -> glyph index (-1 if not found)")
print("static inline int kata_index(uint16_t code) {")
print("  // Binary search on kata_codes (trend: sorted)")
print("  int lo = 0, hi = KATA_N - 1;")
print("  while (lo <= hi) {")
print("    int mid = (lo + hi) >> 1;")
print("    if (kata_codes[mid] == code) return mid;")
print("    if (kata_codes[mid] < code) lo = mid + 1;")
print("    else hi = mid - 1;")
print("  }")
print("  return -1;")
print("}")
