Import("env")

# Single source of truth for the firmware version: the VERSION file at the
# repo root (make_release.sh already gates releases on it). This script runs
# on every build and writes src/version_gen.h, which main.cpp includes — so
# the boot banner and About screen can never disagree with VERSION again.
#
# Why a generated header instead of -D: pioarduino 55.x builds the P4
# framework through its IDF integration, and env CPPDEFINES do not reach the
# app compilation there (verified: MATRIX_VERSION absent from compile_commands
# for main.cpp). The include path (-I src, already required there for the
# sdkconfig.h override) does reach it.

version_file = env.subst("${PROJECT_DIR}/VERSION")
header_dir = env.subst("${PROJECT_DIR}") + "/src"
header = header_dir + "/version_gen.h"

with open(version_file) as f:
    ver = f.read().strip()
assert ver, "VERSION file is empty"

content = (
    "// Generated by src/version.py at build time — do not edit, do not commit.\n"
    "// Source of truth: VERSION at the repo root.\n"
    "#pragma once\n"
    '#define MATRIX_VERSION "v%s"\n' % ver
)

try:
    old = open(header).read()
except OSError:
    old = ""

if old != content:  # only touch mtime when it changed — no needless recompiles
    with open(header, "w") as f:
        f.write(content)

print("Version from VERSION file: v%s -> src/version_gen.h" % ver)
